DROP TABLE IF EXISTS traveller CASCADE;

CREATE TABLE traveller (
  traveller_id SERIAL PRIMARY KEY,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  sub_id VARCHAR(255) NOT NULL,
  home VARCHAR(255) NOT NULL
);