export const mockData = {
  id: "18467-2311031100--31954-0-18450-2311031325|18450-2311101420--31954-0-18467-2311102015",
  price: {
    raw: 393.99,
    formatted: "$394",
  },
  legs: [
    {
      id: "18467-2311031100--31954-0-18450-2311031325",
      origin: {
        id: "YYZ",
        name: "Toronto Pearson International",
        displayCode: "YYZ",
        city: "Toronto",
        isHighlighted: false,
      },
      destination: {
        id: "YYC",
        name: "Calgary",
        displayCode: "YYC",
        city: "Calgary",
        isHighlighted: false,
      },
      durationInMinutes: 265,
      stopCount: 0,
      isSmallestStops: false,
      departure: "2023-11-03T11:00:00",
      arrival: "2023-11-03T13:25:00",
      timeDeltaInDays: 0,
      carriers: {
        marketing: [
          {
            id: -31954,
            logoUrl: "https://logos.skyscnr.com/images/airlines/favicon/PD.png",
            name: "Porter Airlines (Canada) Ltd",
          },
        ],
        operationType: "fully_operated",
      },
      segments: [
        {
          id: "18467-18450-2311031100-2311031325--31954",
          origin: {
            flightPlaceId: "YYZ",
            displayCode: "YYZ",
            parent: {
              flightPlaceId: "YTOA",
              displayCode: "YTO",
              name: "Toronto",
              type: "City",
            },
            name: "Toronto Pearson International",
            type: "Airport",
          },
          destination: {
            flightPlaceId: "YYC",
            displayCode: "YYC",
            parent: {
              flightPlaceId: "YYCA",
              displayCode: "YYC",
              name: "Calgary",
              type: "City",
            },
            name: "Calgary",
            type: "Airport",
          },
          departure: "2023-11-03T11:00:00",
          arrival: "2023-11-03T13:25:00",
          durationInMinutes: 265,
          flightNumber: "357",
          marketingCarrier: {
            id: -31954,
            name: "Porter Airlines (Canada) Ltd",
            alternateId: "PD",
            allianceId: 0,
            displayCode: "",
          },
          operatingCarrier: {
            id: -31954,
            name: "Porter Airlines (Canada) Ltd",
            alternateId: "PD",
            allianceId: 0,
            displayCode: "",
          },
        },
      ],
    },
    {
      id: "18450-2311101420--31954-0-18467-2311102015",
      origin: {
        id: "YYC",
        name: "Calgary",
        displayCode: "YYC",
        city: "Calgary",
        isHighlighted: false,
      },
      destination: {
        id: "YYZ",
        name: "Toronto Pearson International",
        displayCode: "YYZ",
        city: "Toronto",
        isHighlighted: false,
      },
      durationInMinutes: 235,
      stopCount: 0,
      isSmallestStops: false,
      departure: "2023-11-10T14:20:00",
      arrival: "2023-11-10T20:15:00",
      timeDeltaInDays: 0,
      carriers: {
        marketing: [
          {
            id: -31954,
            logoUrl: "https://logos.skyscnr.com/images/airlines/favicon/PD.png",
            name: "Porter Airlines (Canada) Ltd",
          },
        ],
        operationType: "fully_operated",
      },
      segments: [
        {
          id: "18450-18467-2311101420-2311102015--31954",
          origin: {
            flightPlaceId: "YYC",
            displayCode: "YYC",
            parent: {
              flightPlaceId: "YYCA",
              displayCode: "YYC",
              name: "Calgary",
              type: "City",
            },
            name: "Calgary",
            type: "Airport",
          },
          destination: {
            flightPlaceId: "YYZ",
            displayCode: "YYZ",
            parent: {
              flightPlaceId: "YTOA",
              displayCode: "YTO",
              name: "Toronto",
              type: "City",
            },
            name: "Toronto Pearson International",
            type: "Airport",
          },
          departure: "2023-11-10T14:20:00",
          arrival: "2023-11-10T20:15:00",
          durationInMinutes: 235,
          flightNumber: "360",
          marketingCarrier: {
            id: -31954,
            name: "Porter Airlines (Canada) Ltd",
            alternateId: "PD",
            allianceId: 0,
            displayCode: "",
          },
          operatingCarrier: {
            id: -31954,
            name: "Porter Airlines (Canada) Ltd",
            alternateId: "PD",
            allianceId: 0,
            displayCode: "",
          },
        },
      ],
    },
  ],
  isSelfTransfer: false,
  isProtectedSelfTransfer: false,
  farePolicy: {
    isChangeAllowed: false,
    isPartiallyChangeable: false,
    isCancellationAllowed: false,
    isPartiallyRefundable: false,
  },
  fareAttributes: {},
  isMashUp: false,
  hasFlexibleOptions: false,
  score: 0.999,
};
